source 'https://rubygems.org'

gem 'actionpack', '5.1.5.rc1'
gem 'activesupport', '~> 5.1'

gem 'rails', '~> 5.1.4'
gem 'mysql2', '0.4.10'

gem 'therubyracer'
gem 'less-rails', git: 'https://github.com/MustafaZain/less-rails'
gem 'twitter-bootstrap-rails'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '2.4.1'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.7'

group :development, :test do
  gem 'rubocop'
  gem 'puma'
  gem 'rack'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
  #gem 'capybara', '~>3'
  #gem 'capybara'
  gem 'capybara', '2.15'
  #gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'database_rewinder'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

