# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'bootsnap', '>= 1.1.0', require: false
gem 'coffee-rails', '~> 4.2'
gem 'jbuilder', '~> 2.5'
gem 'mysql2', '>= 0.4.4', '< 0.6.0'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.0'
gem 'sass-rails', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  # for debug
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'pry-rails'
  # for test
  gem 'rspec-rails'
  gem 'factory_bot_rails'

  gem 'beautiful-log'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'web-console', '>= 3.3.0'
  # for test
  gem 'spring-commands-rspec'

  gem 'fablicop', require: false
end

group :test do
  gem 'capybara'
  gem 'launchy'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

gem 'enum_help'

gem 'kaminari'

gem 'bootstrap', '~> 4.1.1'
gem 'jquery-rails'

gem 'font-awesome-rails'
